"""sprint 25-26 part 2: dynamic packaging bundle discount

Revision ID: 0efda2ae6204
Revises: 8071d46280b8
Create Date: 2026-09-03 10:23:16.702443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efda2ae6204'
down_revision: Union[str, None] = '8071d46280b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bookings',
        sa.Column('bundle_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'bundle_discount_amount')
    # ### end Alembic commands ###
