"""add rent-a-car module

Revision ID: 103e64d2b3e9
Revises: dcf1128d8d19
Create Date: 2026-09-01 13:49:25.098756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103e64d2b3e9'
down_revision: Union[str, None] = 'dcf1128d8d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate doesn't detect new values on an existing native enum type
    # (see the taggable_entity_type precedent from earlier sprints). Seeding a
    # CommissionRule row that *uses* VEHICLE_RENTAL has to wait for a follow-up
    # migration — Postgres won't let a brand-new enum value be used in the same
    # transaction that added it.
    op.execute("ALTER TYPE taggable_entity_type ADD VALUE IF NOT EXISTS 'VEHICLE'")
    op.execute("ALTER TYPE booking_item_type ADD VALUE IF NOT EXISTS 'VEHICLE_RENTAL'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rent_a_car_role_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rent_a_car_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_rent_a_car_role_id'), 'drivers', ['rent_a_car_role_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rent_a_car_role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_driver_id', sa.UUID(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('SEDAN', 'SUV', 'VAN', 'MICROBUS', 'MOTORCYCLE', 'PICKUP', name='vehicle_type'), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', name='transmission_type'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('with_driver', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', name='vehicle_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rent_a_car_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_rent_a_car_role_id'), 'vehicles', ['rent_a_car_role_id'], unique=False)
    op.create_table('vehicle_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'date', name='uq_vehicle_availability_date')
    )
    op.create_index(op.f('ix_vehicle_availability_vehicle_id'), 'vehicle_availability', ['vehicle_id'], unique=False)
    op.add_column('booking_items', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'booking_items', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_items', type_='foreignkey')
    op.drop_column('booking_items', 'vehicle_id')
    op.drop_index(op.f('ix_vehicle_availability_vehicle_id'), table_name='vehicle_availability')
    op.drop_table('vehicle_availability')
    op.drop_index(op.f('ix_vehicles_rent_a_car_role_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_rent_a_car_role_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
