"""sprint 19-20 part 1: rate plans and advanced pricing

Revision ID: 1bbde24b7805
Revises: ebba73b1c0c6
Create Date: 2026-09-01 23:31:25.166939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbde24b7805'
down_revision: Union[str, None] = 'ebba73b1c0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate_type', sa.Enum('SEASONAL', 'WEEKEND', 'CORPORATE', 'GROUP', 'EARLY_BIRD', name='rate_plan_type'), nullable=False),
    sa.Column('adjustment_type', sa.Enum('PERCENTAGE', 'FIXED_PRICE', name='rate_plan_adjustment_type'), nullable=False),
    sa.Column('adjustment_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('applies_to_weekends', sa.Boolean(), nullable=False),
    sa.Column('min_days_before_checkin', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_plans_room_type_id'), 'rate_plans', ['room_type_id'], unique=False)
    op.add_column(
        'bookings',
        sa.Column('tax_service_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.add_column('properties', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('properties', sa.Column('service_charge_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('room_types', sa.Column('min_stay_nights', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'min_stay_nights')
    op.drop_column('properties', 'service_charge_rate')
    op.drop_column('properties', 'tax_rate')
    op.drop_column('bookings', 'tax_service_amount')
    op.drop_index(op.f('ix_rate_plans_room_type_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    # ### end Alembic commands ###
