"""sprint 23-24 part 1: ical sync for stays

Revision ID: 2f744d228be5
Revises: b89bf42e6115
Create Date: 2026-09-02 13:10:39.243800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f744d228be5'
down_revision: Union[str, None] = 'b89bf42e6115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('ical_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'room_types', ['ical_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_types', type_='unique')
    op.drop_column('room_types', 'ical_token')
    # ### end Alembic commands ###
