"""expand custom tour bidding with structured fields and questions

Revision ID: 372e51c4ea41
Revises: 754981175339
Create Date: 2026-09-21 06:03:25.058272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '372e51c4ea41'
down_revision: Union[str, None] = '754981175339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('asked_by_role_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asked_by_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['custom_tour_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_questions_asked_by_role_id'), 'request_questions', ['asked_by_role_id'], unique=False)
    op.create_index(op.f('ix_request_questions_request_id'), 'request_questions', ['request_id'], unique=False)
    # server_default backfills existing rows on every NOT NULL column below (both
    # tables already have live data) — matches the models' Python-side defaults for
    # new rows going forward, then the defaults are dropped so future inserts must
    # go through the ORM/schema defaults rather than relying on the DB silently.
    op.add_column('custom_tour_requests', sa.Column('adults', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('custom_tour_requests', sa.Column('children', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('custom_tour_requests', sa.Column('infants', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('custom_tour_requests', sa.Column('pickup_location', sa.String(length=255), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('food_preference', sa.Text(), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('accessibility_needs', sa.Text(), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('safety_privacy_notes', sa.Text(), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('guide_requested', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('custom_tour_requests', sa.Column('special_occasion', sa.String(length=255), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.add_column('custom_tour_requests', sa.Column('bid_deadline', sa.Date(), nullable=True))
    op.add_column('tour_bids', sa.Column('stay_name', sa.String(length=255), nullable=True))
    op.add_column('tour_bids', sa.Column('transport_details', sa.Text(), nullable=True))
    op.add_column('tour_bids', sa.Column('food_menu', sa.Text(), nullable=True))
    op.add_column('tour_bids', sa.Column('included_services', sa.Text(), nullable=True))
    op.add_column('tour_bids', sa.Column('excluded_services', sa.Text(), nullable=True))
    op.add_column('tour_bids', sa.Column('addons', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('tour_bids', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tour_bids', sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tour_bids', sa.Column('cancellation_terms', sa.Text(), nullable=True))
    op.add_column('tour_bids', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('tour_bids', sa.Column('is_shortlisted', sa.Boolean(), nullable=False, server_default=sa.false()))

    for table, column in [
        ('custom_tour_requests', 'adults'),
        ('custom_tour_requests', 'children'),
        ('custom_tour_requests', 'infants'),
        ('custom_tour_requests', 'guide_requested'),
        ('tour_bids', 'addons'),
        ('tour_bids', 'is_shortlisted'),
    ]:
        op.alter_column(table, column, server_default=None)

    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NEW_QUESTION'")
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'QUESTION_ANSWERED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_bids', 'is_shortlisted')
    op.drop_column('tour_bids', 'valid_until')
    op.drop_column('tour_bids', 'cancellation_terms')
    op.drop_column('tour_bids', 'deposit_amount')
    op.drop_column('tour_bids', 'tax_amount')
    op.drop_column('tour_bids', 'addons')
    op.drop_column('tour_bids', 'excluded_services')
    op.drop_column('tour_bids', 'included_services')
    op.drop_column('tour_bids', 'food_menu')
    op.drop_column('tour_bids', 'transport_details')
    op.drop_column('tour_bids', 'stay_name')
    op.drop_column('custom_tour_requests', 'bid_deadline')
    op.drop_column('custom_tour_requests', 'additional_notes')
    op.drop_column('custom_tour_requests', 'special_occasion')
    op.drop_column('custom_tour_requests', 'guide_requested')
    op.drop_column('custom_tour_requests', 'safety_privacy_notes')
    op.drop_column('custom_tour_requests', 'accessibility_needs')
    op.drop_column('custom_tour_requests', 'food_preference')
    op.drop_column('custom_tour_requests', 'pickup_location')
    op.drop_column('custom_tour_requests', 'infants')
    op.drop_column('custom_tour_requests', 'children')
    op.drop_column('custom_tour_requests', 'adults')
    op.drop_index(op.f('ix_request_questions_request_id'), table_name='request_questions')
    op.drop_index(op.f('ix_request_questions_asked_by_role_id'), table_name='request_questions')
    op.drop_table('request_questions')
    # ### end Alembic commands ###
