"""add custom tour bidding module

Revision ID: 4534725b1fd1
Revises: 8d53a0264555
Create Date: 2026-08-30 23:00:25.913301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4534725b1fd1'
down_revision: Union[str, None] = '8d53a0264555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate doesn't detect new values on an existing native enum type —
    # only new/dropped tables and columns. Add them explicitly (see the taggable_entity_type
    # precedent from Sprint 5-6). Safe to run more than once (IF NOT EXISTS).
    op.execute("ALTER TYPE taggable_entity_type ADD VALUE IF NOT EXISTS 'CUSTOM_TOUR_REQUEST'")
    op.execute("ALTER TYPE booking_item_type ADD VALUE IF NOT EXISTS 'CUSTOM_BID'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NEW_BID'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BID_ACCEPTED'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BID_REJECTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_tour_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_tour_requests_traveler_id'), 'custom_tour_requests', ['traveler_id'], unique=False)
    op.create_table('tour_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('local_expert_role_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='bid_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['local_expert_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['custom_tour_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'local_expert_role_id', name='uq_bid_per_expert_per_request')
    )
    op.create_index(op.f('ix_tour_bids_local_expert_role_id'), 'tour_bids', ['local_expert_role_id'], unique=False)
    op.create_index(op.f('ix_tour_bids_request_id'), 'tour_bids', ['request_id'], unique=False)
    op.add_column('booking_items', sa.Column('custom_bid_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'booking_items', 'tour_bids', ['custom_bid_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_items', type_='foreignkey')
    op.drop_column('booking_items', 'custom_bid_id')
    op.drop_index(op.f('ix_tour_bids_request_id'), table_name='tour_bids')
    op.drop_index(op.f('ix_tour_bids_local_expert_role_id'), table_name='tour_bids')
    op.drop_table('tour_bids')
    op.drop_index(op.f('ix_custom_tour_requests_traveler_id'), table_name='custom_tour_requests')
    op.drop_table('custom_tour_requests')
    # ### end Alembic commands ###
