"""sprint 21-22 part 1: fraud and risk engine

Revision ID: 4713e02c134b
Revises: 7f6274e2228d
Create Date: 2026-09-02 11:31:11.466561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4713e02c134b'
down_revision: Union[str, None] = '7f6274e2228d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'FRAUD_ALERT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('DUPLICATE_IDENTITY_DOCUMENT', 'SELF_REFERRAL', 'SELF_REVIEW', 'SELF_BOOKING', 'RAPID_CANCELLATION_PATTERN', name='fraud_rule_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='fraud_severity'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='fraud_flag_status'), nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rule_type', 'context_id', name='uq_fraud_flag_dedupe')
    )
    op.create_index(op.f('ix_fraud_flags_user_id'), 'fraud_flags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_flags_user_id'), table_name='fraud_flags')
    op.drop_table('fraud_flags')
    # ### end Alembic commands ###
