"""sprint 27-28: loyalty wallet and promotional credit system

Revision ID: 5136324a57a0
Revises: 0efda2ae6204
Create Date: 2026-09-03 12:55:26.462688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5136324a57a0'
down_revision: Union[str, None] = '0efda2ae6204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=True)
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='promo_discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('max_redemptions_per_user', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('EARNED', 'REDEEMED', 'REFUNDED', 'ADMIN_ADJUSTMENT', name='loyalty_transaction_reason'), nullable=False),
    sa.Column('points_delta', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_booking_id'), 'loyalty_transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_user_id'), 'loyalty_transactions', ['user_id'], unique=False)
    op.create_table('promo_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'booking_id', name='uq_promo_redemption_booking')
    )
    op.create_index(op.f('ix_promo_redemptions_promo_code_id'), 'promo_redemptions', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_promo_redemptions_user_id'), 'promo_redemptions', ['user_id'], unique=False)
    op.add_column('bookings', sa.Column('loyalty_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('promo_discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'promo_discount_amount')
    op.drop_column('bookings', 'loyalty_discount_amount')
    op.drop_index(op.f('ix_promo_redemptions_user_id'), table_name='promo_redemptions')
    op.drop_index(op.f('ix_promo_redemptions_promo_code_id'), table_name='promo_redemptions')
    op.drop_table('promo_redemptions')
    op.drop_index(op.f('ix_loyalty_transactions_user_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_booking_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_loyalty_accounts_user_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    # ### end Alembic commands ###
