"""add effective and expiry dates to commission rules

Revision ID: 694ee83d4d9d
Revises: 79291d86ec18
Create Date: 2026-09-21 21:08:11.504174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694ee83d4d9d'
down_revision: Union[str, None] = '79291d86ec18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_rules', sa.Column('effective_date', sa.Date(), nullable=True))
    op.add_column('commission_rules', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_rules', 'expiry_date')
    op.drop_column('commission_rules', 'effective_date')
    # ### end Alembic commands ###
