"""add image storage: tour_images, property_images, profile photo columns

Revision ID: 6c98180c305a
Revises: 26575a987dda
Create Date: 2026-08-30 14:35:27.494849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c98180c305a'
down_revision: Union[str, None] = '26575a987dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('host_profiles', sa.Column('photo_key', sa.String(length=500), nullable=True))
    op.add_column('host_profiles', sa.Column('photo_content_type', sa.String(length=100), nullable=True))
    op.add_column('local_expert_profiles', sa.Column('photo_key', sa.String(length=500), nullable=True))
    op.add_column('local_expert_profiles', sa.Column('photo_content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_expert_profiles', 'photo_content_type')
    op.drop_column('local_expert_profiles', 'photo_key')
    op.drop_column('host_profiles', 'photo_content_type')
    op.drop_column('host_profiles', 'photo_key')
    op.drop_table('tour_images')
    op.drop_table('property_images')
    # ### end Alembic commands ###
