"""expand tour builder with type pricing policies safety fields

Revision ID: 754981175339
Revises: fffe54d89b9b
Create Date: 2026-09-21 01:03:46.879672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '754981175339'
down_revision: Union[str, None] = 'fffe54d89b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_activities', sa.Column('duration_hours', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('tour_activities', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('tour_activities', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('tour_activities', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('tour_activities', sa.Column('equipment_needed', sa.Text(), nullable=True))
    op.add_column('tour_activities', sa.Column('max_capacity', sa.Integer(), nullable=True))
    op.add_column('tour_activities', sa.Column('safety_notes', sa.Text(), nullable=True))
    # server_default backfills existing rows (some tours already have activities);
    # matches the model's Python-side default=False for new rows going forward.
    op.add_column(
        'tour_activities',
        sa.Column('guide_required', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('tour_activities', 'guide_required', server_default=None)
    op.add_column('tour_itineraries', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('tour_itineraries', sa.Column('arrival_time', sa.String(length=20), nullable=True))
    op.add_column('tour_itineraries', sa.Column('departure_time', sa.String(length=20), nullable=True))
    op.add_column('tour_stays', sa.Column('property_type', sa.String(length=100), nullable=True))
    op.add_column('tour_stays', sa.Column('room_category', sa.String(length=100), nullable=True))
    op.add_column('tour_transport', sa.Column('vehicle_type', sa.String(length=100), nullable=True))
    op.add_column('tour_transport', sa.Column('has_ac', sa.Boolean(), nullable=True))
    op.add_column('tour_transport', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('tour_transport', sa.Column('driver_name', sa.String(length=255), nullable=True))
    tour_type_enum = postgresql.ENUM(
        'ADVENTURE', 'ROMANTIC', 'CULTURAL', 'WILDLIFE', 'BEACH', 'FAMILY', 'TREKKING', 'CITY', 'CRUISE', 'RELIGIOUS',
        name='tour_type',
    )
    tour_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tours', sa.Column('tour_type', tour_type_enum, nullable=True))
    op.add_column('tours', sa.Column('child_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tours', sa.Column('infant_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tours', sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('tours', sa.Column('service_charge_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('tours', sa.Column('deposit_percentage', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('tours', sa.Column('payment_deadline_days', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('cancellation_policy', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('refund_policy', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('child_policy', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True))
    op.add_column('tours', sa.Column('weather_risk_note', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('activity_risk_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'activity_risk_note')
    op.drop_column('tours', 'weather_risk_note')
    op.drop_column('tours', 'emergency_contact_phone')
    op.drop_column('tours', 'child_policy')
    op.drop_column('tours', 'refund_policy')
    op.drop_column('tours', 'cancellation_policy')
    op.drop_column('tours', 'payment_deadline_days')
    op.drop_column('tours', 'deposit_percentage')
    op.drop_column('tours', 'service_charge_rate')
    op.drop_column('tours', 'tax_rate')
    op.drop_column('tours', 'infant_price')
    op.drop_column('tours', 'child_price')
    op.drop_column('tours', 'tour_type')
    postgresql.ENUM(name='tour_type').drop(op.get_bind(), checkfirst=True)
    op.drop_column('tour_transport', 'driver_name')
    op.drop_column('tour_transport', 'capacity')
    op.drop_column('tour_transport', 'has_ac')
    op.drop_column('tour_transport', 'vehicle_type')
    op.drop_column('tour_stays', 'room_category')
    op.drop_column('tour_stays', 'property_type')
    op.drop_column('tour_itineraries', 'departure_time')
    op.drop_column('tour_itineraries', 'arrival_time')
    op.drop_column('tour_itineraries', 'location_name')
    op.drop_column('tour_activities', 'guide_required')
    op.drop_column('tour_activities', 'safety_notes')
    op.drop_column('tour_activities', 'max_capacity')
    op.drop_column('tour_activities', 'equipment_needed')
    op.drop_column('tour_activities', 'min_age')
    op.drop_column('tour_activities', 'difficulty')
    op.drop_column('tour_activities', 'location_name')
    op.drop_column('tour_activities', 'duration_hours')
    # ### end Alembic commands ###
