"""homepage CMS: settings, featured listings, category tiles

Revision ID: 7d947b797b38
Revises: 5a3f9e1c7b28
Create Date: 2026-09-26 11:11:34.809013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7d947b797b38'
down_revision: Union[str, None] = '5a3f9e1c7b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('image_content_type', sa.String(length=100), nullable=True),
    sa.Column('gradient_from', sa.String(length=20), nullable=False),
    sa.Column('gradient_to', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('featured_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    # postgresql.ENUM + create_type=False — taggable_entity_type already exists
    # (locations/models.py); plain sa.Enum's create_type flag is ignored by
    # op.create_table in this setup, same fix as ebba73b1c0c6's AdCampaign.entity_type.
    sa.Column('entity_type', postgresql.ENUM('PARTNER_ROLE', 'TOUR', 'PROPERTY', 'CUSTOM_TOUR_REQUEST', 'VEHICLE', 'AD_CAMPAIGN', name='taggable_entity_type', create_type=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_featured_listings_entity_id'), 'featured_listings', ['entity_id'], unique=False)
    op.create_table('homepage_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hero_badge_text', sa.String(length=255), nullable=False),
    sa.Column('hero_headline', sa.String(length=255), nullable=False),
    sa.Column('hero_subheadline', sa.Text(), nullable=False),
    sa.Column('hero_image_key', sa.String(length=500), nullable=True),
    sa.Column('hero_image_content_type', sa.String(length=100), nullable=True),
    sa.Column('destinations_heading', sa.String(length=255), nullable=False),
    sa.Column('destinations_subheading', sa.String(length=500), nullable=False),
    sa.Column('tours_heading', sa.String(length=255), nullable=False),
    sa.Column('tours_subheading', sa.String(length=500), nullable=False),
    sa.Column('stays_heading', sa.String(length=255), nullable=False),
    sa.Column('stays_subheading', sa.String(length=500), nullable=False),
    sa.Column('banner_heading', sa.String(length=255), nullable=False),
    sa.Column('banner_text', sa.Text(), nullable=False),
    sa.Column('banner_cta_label', sa.String(length=100), nullable=False),
    sa.Column('banner_cta_link', sa.String(length=500), nullable=False),
    sa.Column('banner_image_key', sa.String(length=500), nullable=True),
    sa.Column('banner_image_content_type', sa.String(length=100), nullable=True),
    sa.Column('category_heading', sa.String(length=255), nullable=False),
    sa.Column('category_subheading', sa.String(length=500), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_settings')
    op.drop_index(op.f('ix_featured_listings_entity_id'), table_name='featured_listings')
    op.drop_table('featured_listings')
    op.drop_table('category_tiles')
    # ### end Alembic commands ###
