"""sprint 19-20 part 2: staff, rooms, front-desk booking

Revision ID: 7f6274e2228d
Revises: 1bbde24b7805
Create Date: 2026-09-02 10:54:15.794540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6274e2228d'
down_revision: Union[str, None] = '1bbde24b7805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'STAFF_INVITE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('staff_role', sa.Enum('MANAGER', 'FRONT_DESK', 'HOUSEKEEPING', name='staff_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='staff_status'), nullable=False),
    sa.Column('invited_by_role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'user_id', name='uq_property_staff_user')
    )
    op.create_index(op.f('ix_property_staff_property_id'), 'property_staff', ['property_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('housekeeping_status', sa.Enum('CLEAN', 'DIRTY', 'CLEANING_IN_PROGRESS', 'OUT_OF_ORDER', name='housekeeping_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'room_number', name='uq_room_number_per_type')
    )
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.add_column('booking_items', sa.Column('assigned_room_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'booking_items', 'rooms', ['assigned_room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_items', type_='foreignkey')
    op.drop_column('booking_items', 'assigned_room_id')
    op.drop_index(op.f('ix_rooms_room_type_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_property_staff_property_id'), table_name='property_staff')
    op.drop_table('property_staff')
    # ### end Alembic commands ###
