"""add performance indexes on hot FK columns

Revision ID: 8d53a0264555
Revises: 5939790010a3
Create Date: 2026-08-30 21:31:53.933541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d53a0264555'
down_revision: Union[str, None] = '5939790010a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_commissions_partner_role_id'), 'commissions', ['partner_role_id'], unique=False)
    op.create_index(op.f('ix_location_tags_location_id'), 'location_tags', ['location_id'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reviews_property_id'), 'reviews', ['property_id'], unique=False)
    op.create_index(op.f('ix_reviews_tour_id'), 'reviews', ['tour_id'], unique=False)
    op.create_index(op.f('ix_room_types_property_id'), 'room_types', ['property_id'], unique=False)
    op.create_index(op.f('ix_tour_departures_tour_id'), 'tour_departures', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_departures_tour_id'), table_name='tour_departures')
    op.drop_index(op.f('ix_room_types_property_id'), table_name='room_types')
    op.drop_index(op.f('ix_reviews_tour_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_property_id'), table_name='reviews')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_location_tags_location_id'), table_name='location_tags')
    op.drop_index(op.f('ix_commissions_partner_role_id'), table_name='commissions')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    # ### end Alembic commands ###
