"""verification trust: document expiry and badge validity/revocation

Revision ID: 8eccd4bd4c72
Revises: c148f32762e5
Create Date: 2026-09-24 22:11:54.241278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eccd4bd4c72'
down_revision: Union[str, None] = 'c148f32762e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('revocation_reason', sa.Text(), nullable=True))
    op.add_column('badges', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('partner_documents', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate doesn't detect new values on an existing native enum.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE badge_status ADD VALUE IF NOT EXISTS 'REVOKED'")
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'DOCUMENT_EXPIRING'")
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'BADGE_REVOKED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_documents', 'expiry_date')
    op.drop_column('badges', 'expiry_date')
    op.drop_column('badges', 'revocation_reason')
    # ### end Alembic commands ###
    # Postgres cannot drop enum values.
