"""add financial engine and trust badges

Revision ID: 90d30f4af0fc
Revises: e51149ef4443
Create Date: 2026-09-01 12:20:13.645781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '90d30f4af0fc'
down_revision: Union[str, None] = 'e51149ef4443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate doesn't detect new values on an existing native enum type
    # (see the taggable_entity_type precedent from earlier sprints) — commissions.status
    # (`commission_status`) already exists with PENDING/PAYABLE; add the new PAID value.
    op.execute("ALTER TYPE commission_status ADD VALUE IF NOT EXISTS 'PAID'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('PARTNER_ROLE', 'TOUR', 'PROPERTY', 'CUSTOM_TOUR_REQUEST', name='taggable_entity_type', create_type=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('badge_type', sa.Enum('VERIFIED', 'TOP_RATED', 'COUPLE_FRIENDLY', 'SAFETY_CERTIFIED', name='badge_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='badge_status'), nullable=False),
    sa.Column('is_auto_awarded', sa.Boolean(), nullable=False),
    sa.Column('applied_by_user_id', sa.UUID(), nullable=True),
    sa.Column('private_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'badge_type', name='uq_badge_per_entity_type')
    )
    op.create_index(op.f('ix_badges_entity_id'), 'badges', ['entity_id'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('CATEGORY', 'PARTNER', 'NETWORK', name='commission_rule_scope'), nullable=False),
    sa.Column('item_type', postgresql.ENUM('TOUR_DEPARTURE', 'ROOM_TYPE', 'CUSTOM_BID', name='booking_item_type', create_type=False), nullable=True),
    sa.Column('partner_role_id', sa.UUID(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_role_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PAID', name='payout_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_partner_role_id'), 'payouts', ['partner_role_id'], unique=False)
    op.add_column('business_referrals', sa.Column('linked_partner_role_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'business_referrals', ['linked_partner_role_id'])
    op.create_foreign_key(None, 'business_referrals', 'partner_roles', ['linked_partner_role_id'], ['id'], ondelete='SET NULL')
    # A brand-new enum type added via ALTER TABLE ADD COLUMN (unlike CREATE TABLE)
    # needs its CREATE TYPE emitted explicitly first — op.create_table's DDL compiler
    # auto-creates a column's enum type, but op.add_column's doesn't.
    op.execute("CREATE TYPE commission_source AS ENUM ('DIRECT', 'NETWORK')")
    op.add_column(
        'commissions',
        sa.Column(
            'source',
            postgresql.ENUM('DIRECT', 'NETWORK', name='commission_source', create_type=False),
            nullable=False,
            server_default='DIRECT',  # backfills existing rows — every commission before this migration was a DIRECT one
        ),
    )
    op.add_column('commissions', sa.Column('rule_id', sa.UUID(), nullable=True))
    op.add_column('commissions', sa.Column('payout_id', sa.UUID(), nullable=True))
    op.drop_constraint('commissions_booking_item_id_key', 'commissions', type_='unique')
    op.create_index(op.f('ix_commissions_booking_item_id'), 'commissions', ['booking_item_id'], unique=False)
    op.create_unique_constraint('uq_commission_per_item_partner_source', 'commissions', ['booking_item_id', 'partner_role_id', 'source'])
    op.create_foreign_key(None, 'commissions', 'commission_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'commissions', 'payouts', ['payout_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed the default CATEGORY/NETWORK rules so the rules engine is visibly
    # configurable from day one, rather than relying on the code-level fallback
    # constants in commissions/service.py (which only exist as a safety net for
    # if these rows are ever deleted without a replacement).
    op.execute(
        """
        INSERT INTO commission_rules (id, scope, item_type, partner_role_id, rate, is_active, created_at, updated_at)
        VALUES
            (gen_random_uuid(), 'CATEGORY', 'TOUR_DEPARTURE', NULL, 0.10, true, now(), now()),
            (gen_random_uuid(), 'CATEGORY', 'ROOM_TYPE', NULL, 0.12, true, now(), now()),
            (gen_random_uuid(), 'CATEGORY', 'CUSTOM_BID', NULL, 0.10, true, now(), now()),
            (gen_random_uuid(), 'NETWORK', NULL, NULL, 0.02, true, now(), now())
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_constraint('uq_commission_per_item_partner_source', 'commissions', type_='unique')
    op.drop_index(op.f('ix_commissions_booking_item_id'), table_name='commissions')
    op.create_unique_constraint('commissions_booking_item_id_key', 'commissions', ['booking_item_id'])
    op.drop_column('commissions', 'payout_id')
    op.drop_column('commissions', 'rule_id')
    op.drop_column('commissions', 'source')
    op.drop_constraint(None, 'business_referrals', type_='foreignkey')
    op.drop_constraint(None, 'business_referrals', type_='unique')
    op.drop_column('business_referrals', 'linked_partner_role_id')
    op.drop_index(op.f('ix_payouts_partner_role_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_badges_entity_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
