"""guide certification and tour activity high-risk flag

Revision ID: c148f32762e5
Revises: a1c9f3e7b204
Create Date: 2026-09-22 14:23:11.127359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c148f32762e5'
down_revision: Union[str, None] = 'a1c9f3e7b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_role_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('NONE', 'LEVEL_1', 'LEVEL_2', name='guide_certification_level'), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('restriction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_role_id')
    )
    # server_default backfills existing rows (tour_activities already has live data);
    # dropped afterward so it matches the model's own Python-side default going forward.
    op.add_column('tour_activities', sa.Column('is_high_risk', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('tour_activities', 'is_high_risk', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_activities', 'is_high_risk')
    op.drop_table('guide_certifications')
    # ### end Alembic commands ###
