"""expand business referral network with invites verification and custom commission

Revision ID: e0a183f58d74
Revises: 372e51c4ea41
Create Date: 2026-09-21 07:08:08.672271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a183f58d74'
down_revision: Union[str, None] = '372e51c4ea41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_referrals', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.add_column('business_referrals', sa.Column('invite_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_referrals', sa.Column('invited_user_id', sa.UUID(), nullable=True))
    op.add_column('business_referrals', sa.Column('invite_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # server_default backfills the 2 existing rows, then is dropped so future
    # inserts go through the model's Python-side default instead.
    op.add_column(
        'business_referrals', sa.Column('is_business_verified', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('business_referrals', 'is_business_verified', server_default=None)
    op.add_column('business_referrals', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_referrals', sa.Column('custom_commission_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.create_unique_constraint(None, 'business_referrals', ['invite_token'])
    op.create_foreign_key(None, 'business_referrals', 'users', ['invited_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_referrals', type_='foreignkey')
    op.drop_constraint(None, 'business_referrals', type_='unique')
    op.drop_column('business_referrals', 'custom_commission_rate')
    op.drop_column('business_referrals', 'verified_at')
    op.drop_column('business_referrals', 'is_business_verified')
    op.drop_column('business_referrals', 'invite_accepted_at')
    op.drop_column('business_referrals', 'invited_user_id')
    op.drop_column('business_referrals', 'invite_sent_at')
    op.drop_column('business_referrals', 'invite_token')
    # ### end Alembic commands ###
