"""add guide supervision and business network modules

Revision ID: e51149ef4443
Revises: 4534725b1fd1
Create Date: 2026-08-30 23:25:39.966544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51149ef4443'
down_revision: Union[str, None] = '4534725b1fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate doesn't detect new values on an existing native enum type —
    # only new/dropped tables and columns. Add them explicitly (see the taggable_entity_type
    # precedent from Sprint 5-6). Safe to run more than once (IF NOT EXISTS).
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'GUIDE_INVITE'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'GUIDE_SUPERVISION_ACCEPTED'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'GUIDE_SUPERVISION_ENDED'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'GUIDE_ASSIGNED'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'REFERRAL_APPROVED'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'REFERRAL_REJECTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referring_expert_role_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ownership_type', sa.Enum('OWNED', 'REFERRED', name='ownership_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='referral_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referring_expert_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_referrals_referring_expert_role_id'), 'business_referrals', ['referring_expert_role_id'], unique=False)
    op.create_table('guide_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_role_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guide_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_role_id', 'date', name='uq_guide_availability_date')
    )
    op.create_index(op.f('ix_guide_availability_guide_role_id'), 'guide_availability', ['guide_role_id'], unique=False)
    op.create_table('guide_supervision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('local_expert_role_id', sa.UUID(), nullable=False),
    sa.Column('guide_role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TERMINATED', name='supervision_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guide_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_expert_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_role_id', name='uq_guide_single_supervisor')
    )
    op.create_index(op.f('ix_guide_supervision_local_expert_role_id'), 'guide_supervision', ['local_expert_role_id'], unique=False)
    op.create_table('guide_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_role_id', sa.UUID(), nullable=False),
    sa.Column('tour_departure_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_role_id', sa.UUID(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', name='assignment_status'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_departure_id'], ['tour_departures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guide_assignments_guide_role_id'), 'guide_assignments', ['guide_role_id'], unique=False)
    op.create_index(op.f('ix_guide_assignments_tour_departure_id'), 'guide_assignments', ['tour_departure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guide_assignments_tour_departure_id'), table_name='guide_assignments')
    op.drop_index(op.f('ix_guide_assignments_guide_role_id'), table_name='guide_assignments')
    op.drop_table('guide_assignments')
    op.drop_index(op.f('ix_guide_supervision_local_expert_role_id'), table_name='guide_supervision')
    op.drop_table('guide_supervision')
    op.drop_index(op.f('ix_guide_availability_guide_role_id'), table_name='guide_availability')
    op.drop_table('guide_availability')
    op.drop_index(op.f('ix_business_referrals_referring_expert_role_id'), table_name='business_referrals')
    op.drop_table('business_referrals')
    # ### end Alembic commands ###
