"""add advertising platform

Revision ID: ebba73b1c0c6
Revises: cbb8b608b6bc
Create Date: 2026-09-01 22:03:57.546875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ebba73b1c0c6'
down_revision: Union[str, None] = 'cbb8b608b6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # taggable_entity_type already exists (locations module) — gained a new member
    # here (AD_CAMPAIGN) rather than a new type, so it needs ADD VALUE, not CREATE TYPE.
    op.execute("ALTER TYPE taggable_entity_type ADD VALUE IF NOT EXISTS 'AD_CAMPAIGN'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_role_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('PARTNER_ROLE', 'TOUR', 'PROPERTY', 'CUSTOM_TOUR_REQUEST', 'VEHICLE', 'AD_CAMPAIGN', name='taggable_entity_type', create_type=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('placement_type', sa.Enum('SEARCH', 'FEATURED', 'BANNER', 'CARD', 'SPONSORED', name='ad_placement_type'), nullable=False),
    sa.Column('billing_model', sa.Enum('CPC', 'CPM', name='ad_billing_model'), nullable=False),
    sa.Column('bid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'REJECTED', 'COMPLETED', name='ad_campaign_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('impressions_count', sa.Integer(), nullable=False),
    sa.Column('clicks_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_entity_id'), 'ad_campaigns', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_partner_role_id'), 'ad_campaigns', ['partner_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_campaigns_partner_role_id'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_entity_id'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
