"""phase 5: esim store via triptel partner api

Revision ID: ebe628d13714
Revises: 5136324a57a0
Create Date: 2026-09-13 08:12:10.226564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe628d13714'
down_revision: Union[str, None] = '5136324a57a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esim_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'PROVISIONING', 'COMPLETED', 'REFUND_PENDING', 'REFUNDED', 'CANCELLED', name='esim_order_status'), nullable=False),
    sa.Column('triptel_product_id', sa.String(length=100), nullable=False),
    sa.Column('product_title', sa.String(length=255), nullable=False),
    sa.Column('country_iso2', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=False),
    sa.Column('data_amount_gb', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_bdt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tran_id', sa.String(length=100), nullable=True),
    sa.Column('val_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triptel_order_id', sa.String(length=100), nullable=True),
    sa.Column('triptel_order_no', sa.String(length=100), nullable=True),
    sa.Column('triptel_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iccid', sa.String(length=50), nullable=True),
    sa.Column('lpa_string', sa.Text(), nullable=True),
    sa.Column('qr_code_data', sa.Text(), nullable=True),
    sa.Column('smdp_address', sa.String(length=255), nullable=True),
    sa.Column('matching_id', sa.String(length=100), nullable=True),
    sa.Column('install_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_by_id', sa.UUID(), nullable=True),
    sa.Column('refund_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['refunded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esim_orders_tran_id'), 'esim_orders', ['tran_id'], unique=True)
    op.create_index(op.f('ix_esim_orders_triptel_order_id'), 'esim_orders', ['triptel_order_id'], unique=False)
    op.create_index(op.f('ix_esim_orders_user_id'), 'esim_orders', ['user_id'], unique=False)
    op.create_table('esim_pricing_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usd_to_bdt_rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rounding_step_bdt', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Alembic autogenerate does not detect new values added to an existing
    # PostgreSQL enum type — these two are added by hand. ALTER TYPE ... ADD VALUE
    # cannot run inside the transaction Alembic normally wraps a migration in, hence
    # the autocommit block (see notifications/models.py's NotificationType).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'esim_ready'")
        op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'esim_failed'")


def downgrade() -> None:
    # Note: PostgreSQL has no ALTER TYPE ... DROP VALUE — the 'esim_ready'/
    # 'esim_failed' notification_type values added in upgrade() cannot be removed
    # here. Harmless to leave behind: an unused enum value with no rows referencing
    # it once esim_orders is gone.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esim_pricing_config')
    op.drop_index(op.f('ix_esim_orders_user_id'), table_name='esim_orders')
    op.drop_index(op.f('ix_esim_orders_triptel_order_id'), table_name='esim_orders')
    op.drop_index(op.f('ix_esim_orders_tran_id'), table_name='esim_orders')
    op.drop_table('esim_orders')
    # ### end Alembic commands ###
