"""add live chat module

Revision ID: f023e6f58693
Revises: 7d47c6cabae8
Create Date: 2026-09-01 14:42:03.604819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f023e6f58693'
down_revision: Union[str, None] = '7d47c6cabae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'NEW_CHAT_MESSAGE'")
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'CHAT_MESSAGE_REPORTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('partner_role_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.Enum('TOUR', 'PROPERTY', 'VEHICLE', 'BOOKING_ITEM', name='chat_context_type'), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='chat_thread_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_role_id'], ['partner_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'partner_role_id', 'context_type', 'context_id', name='uq_chat_thread_context')
    )
    op.create_index(op.f('ix_chat_threads_partner_role_id'), 'chat_threads', ['partner_role_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_traveler_id'), 'chat_threads', ['traveler_id'], unique=False)
    op.create_table('chat_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_attachments_thread_id'), 'chat_attachments', ['thread_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'ATTACHMENT', 'LOCATION', name='chat_message_type'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('was_redacted', sa.Boolean(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('report_reason', sa.Text(), nullable=True),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['chat_attachments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_attachments_thread_id'), table_name='chat_attachments')
    op.drop_table('chat_attachments')
    op.drop_index(op.f('ix_chat_threads_traveler_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_partner_role_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
